---
- name: install based on os family
  hosts: local
  connection: local
  become: yes
  tasks:
  - name: install nginx if os_family is redhat
    ansible.builtin.dnf:
      name: nginx
      state: latest
    when : ansible_os_family == "RedHat" 

  - name: install nginx if ubuntu
    ansible.builtin.apt:
      name: nginx
      state: latest
    when : ansible_os_family = "Debian"    