---
- name: functions or filters
  hosts: local
  connection: local
  vars:
    placeholder: holder
    test1: test1
  tasks:
  - name: default variable when value is not provided
    ansible.builtin.debug:
      msg: "Hello, {{ name }}"
    ignore_errors: true  

# fatal: [localhost]: FAILED! => {"msg": "The task includes an option with an undefined variable. The error was: 'name' is undefined. 'name' is undefined\n\nThe error appears to be in '/home/ec2-user/ansible/17-functions-filters.yaml': line 9, column 5, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n  tasks:\n  - name: default variable when value is not provided\n    ^ here\n"}      

# Handling undefined variables
# Filters can help you manage missing or undefined variables by providing defaults or making some variables optional. If you configure Ansible to ignore most undefined variables, you can mark some variables as requiring values with the mandatory filter

# Providing default values
# You can provide default values for variables directly in your templates using the Jinja2 ‘default’ filter. This is often a better approach than failing if a variable is not defined:

# {{ some_variable | default(5) }}

  - name: default variable 
    ansible.builtin.debug:
      msg: "Hello, {{ name | default('Satya') }}"