---
- name: functions or filters
  hosts: local
  connection: local
  vars:
    placeholder: holder
    technologies: DevOps, Linux, Shell, Ansible
    technologies_hyphen: DevOps - Linux - Shell - Ansible
    test1: test1
    tags:
      Application: payment
      Environment: dev
    listTags:
    - key: Application
      value: payment
    - key: Environment
      value: dev  
  tasks:
  - name: default variable when value is not provided
    ansible.builtin.debug:
      msg: "Hello, {{ name }}"
    ignore_errors: true  

# fatal: [localhost]: FAILED! => {"msg": "The task includes an option with an undefined variable. The error was: 'name' is undefined. 'name' is undefined\n\nThe error appears to be in '/home/ec2-user/ansible/17-functions-filters.yaml': line 9, column 5, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n  tasks:\n  - name: default variable when value is not provided\n    ^ here\n"}      

# Handling undefined variables
# Filters can help you manage missing or undefined variables by providing defaults or making some variables optional. If you configure Ansible to ignore most undefined variables, you can mark some variables as requiring values with the mandatory filter

# Providing default values
# You can provide default values for variables directly in your templates using the Jinja2 ‘default’ filter. This is often a better approach than failing if a variable is not defined:

# {{ some_variable | default(5) }}

  - name: default variable 
    ansible.builtin.debug:
      msg: "Hello, {{ name | default('Satya') }}"

  - name: convert string to lists 
    ansible.builtin.debug:
      msg: "Technologies are: {{ technologies | split(',') }}"

#  For example, if you want to split a string variable fruits by commas, you can use:

# {{ fruits | split(',') }}

  - name: convert string to lists - hyphen separated
    ansible.builtin.debug:
      msg: "Technologies are: {{ technologies_hyphen | split('-') }}"

# ERROR! Invalid variable name in vars specified for Play: 'technologies-hyphen' is not a valid variable name

  - name: convert dictionary / map to lists 
    ansible.builtin.debug:
      msg: "Tags are: {{ tags | dict2items }}"
    # ignore_errors: true  

# "msg": "Tags are: [{'key': 'Application', 'value': 'payment'}, {'key': 'Environment', 'value': 'dev'}]"

  - name: convert lists to dicts 
    ansible.builtin.debug:
      msg: "tag map: {{ listTags | items2dict }}"

#  "msg": "tag map: {'Application': 'payment', 'Environment': 'dev'}"     

# Formatting YAML and JSON

# To read a YAML file and store its content in a variable using set_fact and the lookup plugin in Ansible, perform the following steps:
# Use the lookup plugin to read the file content:
# The lookup('file', 'path/to/your/file.yaml') expression reads the content of the specified file on the Ansible control node.
# Use the from_yaml filter to parse the YAML content:
# The from_yaml filter converts the string content read from the file into a Python dictionary or list, depending on the YAML structure.
# Use set_fact to store the parsed data in a variable:
# The ansible.builtin.set_fact module assigns the result of the lookup and parsing to a new variable.

  - name: read yaml and take into a variable
    ansible.builtin.set_fact:
      student_yaml: "{{ lookup('file', 'student.yaml') | from_yaml }}"  

  - name: convert yaml to json
    ansible.builtin.debug:
      msg: " JSON: {{ student_yaml | to_json  }}" 

# - name: Copy using inline content
#   ansible.builtin.copy:
#     content: '# This file was moved to /etc/other.conf'
#     dest: /etc/mine.conf      

  - name: save student_yaml
    ansible.builtin.copy:
      content: "{{student_yaml}}" 
      dest: ./student-yaml
    ignore_errors: true  

# [{"name": "Name reddy m", "dob": "01-01-01", "age": 21, "addresses": [{"doorNo": "4-32", "street": "gandhi nagar", "city": "hyderabd", "pin": 534565, "type": "current"}, {"doorNo": "4-32", "street": "gandhi nagar", "city": "hyderabd", "pin": 534565, "type": "perm"}], "skills": ["java", "devops", "cloud"]}, {"name": "ramesh", "dob": "01-01-01", "age": 21, "addresses": [{"doorNo": "4-32", "street": "gandhi nagar", "city": "hyderabd", "pin": 534565, "type": "current"}, {"doorNo": "4-32", "street": "gandhi nagar", "city": "hyderabd", "pin": 534565, "type": "perm"}], "skills": ["java", "devops", "cloud"]}]


  - name: save json to file by copying
    ansible.builtin.copy:
      content:  "{{ student_yaml | to_json  }}" 
      dest: ./student-data.json
# [{"name": "Name reddy m", "dob": "01-01-01", "age": 21, "addresses": [{"doorNo": "4-32", "street": "gandhi nagar", "city": "hyderabd", "pin": 534565, "type": "current"}, {"doorNo": "4-32", "street": "gandhi nagar", "city": "hyderabd", "pin": 534565, "type": "perm"}], "skills": ["java", "devops", "cloud"]}, {"name": "ramesh", "dob": "01-01-01", "age": 21, "addresses": [{"doorNo": "4-32", "street": "gandhi nagar", "city": "hyderabd", "pin": 534565, "type": "current"}, {"doorNo": "4-32", "street": "gandhi nagar", "city": "hyderabd", "pin": 534565, "type": "perm"}], "skills": ["java", "devops", "cloud"]}]


  - name: save json to file by copying-nice json
    ansible.builtin.copy:
      content:  "{{ student_yaml | to_nice_json  }}" 
      dest: ./nice-student-data.json

  - name: convert uppercase
    ansible.builtin.debug:
      msg: "{{ name | default('dbskdb') | upper }}"

  - name: convert lowercase
    ansible.builtin.debug:
      msg: "{{ gmail | default('Test@tTTest.com') | lower }}"

  - name: check IP is valid or not
    ansible.builtin.debug: 
      msg: "{{ ipaddress | default('423.123.123.123') | ansible.utils.ipv4 }}"
# "msg": false

# ------------------shell vs command module in ansible--------------------

# The shell and command modules in Ansible both execute commands on target hosts, but they differ in how they interact with the shell environment and handle shell-specific features. 
# command module: 

# • Direct execution: Executes commands directly on the target system without invoking a shell. This means it does not interpret shell-specific features like pipes (|), redirection (&gt;, &gt;&gt;), or logical operators (&&, ||). 
# • Security: Generally considered more secure as it reduces the risk of command injection, as shell metacharacters are not interpreted. 
# • Simplicity: Best suited for simple, straightforward commands or when executing binaries that don't require shell features. [1]  

# shell module: 

# • Shell environment: Executes commands within a shell environment (typically /bin/sh by default, but configurable). This allows the use of shell-specific features. 
# • Flexibility: Provides more flexibility for complex commands involving pipes, redirection, environment variables, or execution of shell scripts. 
# • Security considerations: Requires careful handling, especially when using variables, as it is susceptible to command injection if input is not properly sanitized. 

# Key Differences Summarized: 

# | Feature | command module | shell module  |
# | --- | --- | --- |
# | Shell features | Does not interpret shell features (pipes, etc.) | Interprets shell features (pipes, redirection, etc.)  |
# | Security | More secure; | Less secure;  |
# | Complexity | Best for simple commands and binaries | Best for complex commands and shell scripts  |

# When to use which: 

# • Use command 

# when you need to execute a simple, self-contained command without needing any shell-specific functionalities. 

# • Use shell 

# when you need to leverage shell features like piping, redirection, or chaining commands, or when executing shell scripts. If using variables with shell, ensure they are properly sanitized or quoted to prevent injection. 



  - name: grep for root
    ansible.builtin.command: cat /etc/passwd | grep root
    register: command_output
    ignore_errors: true

  - name: display command_output
    ansible.builtin.debug:
      msg: "{{ command_output }}"
#retured rc 1


  - name: grep for root - shel command
    ansible.builtin.shell: cat /etc/passwd | grep root
    register: command_output_shell
 

  - name: display command_output-shelll
    ansible.builtin.debug:
      msg: "{{ command_output_shell }}"

  - name: redirect the output-command
    ansible.builtin.command: ls -ltr > /tmp/output.txt
    register: redirect_output
    ignore_errors: true

  - name: print redirect_output command
    ansible.builtin.debug:
      msg: "{{ redirect_output }}"

  - name: redirect the output using shell
    ansible.builtin.shell: ls -ltr > /tmp/output.txt
    register: redirect_output

  - name: print redirect_output shell
    ansible.builtin.debug:
      msg: "{{ redirect_output }}"